baseurl = "https://dgavlock.github.io/"
title = "Dillon Gavlock"

theme = "coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "Dillon"

[params]
    author = "Dillon Gavlock"
    description = "This is where I write stuff"
    keywords = "blog,developer,personal"
    info = "Research Technician and Graduate Student"
    avatarurl = "images/dillon300.jpeg"
    footercontent = "I love to create stuff"

    hideCredits = false
    hideCopyright = false

    rtl = false

    # Custom CSS
    custom_css = []

[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/dgavlock/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.com/dgavlock/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/dillongav31/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 4
    url = "https://www.linkedin.com/in/dgavlock/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium fa-2x"
    weight = 5
    url = "https://medium.com/@dgavlock"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Project"
    weight = 3
    url = "/projects/"
[[menu.main]]
    name = "Contact"
    weight = 4
    url = "/contact/"


[languages]
    [languages.en]
        languagename = "English" # The language name to be displayed in the selector.
        title = "Dillon Gavlock"

        # You can configure the theme parameter for each language.
        [languages.en.params]
        author = "Dillon Gavlock"
        info = "Research Technician and Graduate Student"
        description = "Working hard to improve the world in any way."
        keywords = "blog,developer,personal"

        [languages.en.menu] # It is possible to change the menu too.

        [[languages.en.menu.main]]
        name = "About"
        weight = 1.0
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2.0
        url = "/posts/"

        [[languages.en.menu.main]]
        name = "Projects"
        weight = 3
        url = "/projects/"
        [[languages.en.menu.main]]
        name = "Contact"
        weight = 4
        url = "/contact/"
